# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=128),
        ),
    ]
