# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20190322_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
        migrations.AddField(
            model_name='page',
            name='phone',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
